sqlConnStr = "postgres://localhost/bloomapi?sslmode=disable"
searchHosts = [
  "localhost"
]
sourceBinaries = [
"./sources/nucc.hcpt/hcpt",
"./sources/usgov.hhs.hcpcs/hcpcs",
"./sources/usgov.hhs.npi/npi",
"./sources/usgov.hhs.pecos/pecos",
"./sources/usgov.hhs.taxonomy_codes/taxonomy_codes",
]
