sqlConnStr = "postgres://postgres@db/bloomapi?sslmode=disable"
searchHosts = [
  "search"
]
sourceBinaries = [
"./sources/bloomapi.yourchart_locations/yourchart_locations",
"./sources/nucc.hcpt/hcpt",
"./sources/usgov.hhs.aco/aco",
"./sources/usgov.hhs.hcpcs/hcpcs",
"./sources/usgov.hhs.icd10/icd10",
"./sources/usgov.hhs.icd9/icd9",
"./sources/usgov.hhs.icd_gems/icd_gems",
"./sources/usgov.hhs.medicare_utilization/medicare_utilization",
"./sources/usgov.hhs.npi/npi",
"./sources/usgov.hhs.pecos/pecos",
"./sources/usgov.hhs.phycomp/phycomp",
"./sources/usgov.hhs.pos/pos",
"./sources/usgov.hhs.taxonomy_codes/taxonomy_codes",
]
