sourceBinaries = [
  "/Users/untoldone/Source/go/bin/datasources/hcpsc",
  "/Users/untoldone/Source/go/bin/datasources/npi",
  "/Users/untoldone/Source/go/bin/datasources/pecos",
  "/Users/untoldone/Source/go/bin/datasources/taxonomy_codes"
]
sqlConnStr = "postgres://postgres:postgres@localhost/bloomapi?sslmode=disable"
searchHosts = [
  "localhost"
]
